name: null
favicon: null
layout_spectrum: 0.49672
typography_spectrum: 0.48033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#575958'
    - '#4f86bf'
    - '#222a2d'
    - '#c0cad3'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
